META:
  - "dataset/tvl_dataset/ssvtp/finetune_train.json"
  - "dataset/tvl_dataset/hct/data1/finetune_train.json"
  - "dataset/tvl_dataset/hct/data2/finetune_train.json"
  - "dataset/tvl_dataset/hct/data3/finetune_train.json"
